[package]
name = "buddy-rs"
version = "0.1.0"
edition = "2024"
authors = ["Fiaro fiaromiangaly@gmail.com"]
keywords = ["buddy", "terminal", "shell", "tool", "productivity"]
categories = ["command-line-utilities"]
description = "Rust-based shell assistant that monitors your shell commands and provides reactions or feedback."
repository = "https://github.com/Emii-lia/buddy-rs"
homepage = "https://crates.io/crates/buddy-rs"
license = "MIT"

[dependencies]
daemon = { path = "../daemon", version = "0.1.0", package = "buddy-daemon" }
init = { path = "../init", version = "0.1.0", package = "buddy-init" }
shared = { path = "../shared", version = "0.1.0", package = "buddy-shared" }
shell-hook = { path = "../shell-hook", version = "0.1.0", package = "buddy-shell-hook" }
anyhow = "1.0.102"
tokio = { version = "1.52.3", features = ["full"]}