name: Rust

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - '.gitignore'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - '.gitignore'

env:
  CARGO_TERM_COLOR: always
  BUDDY_API_KEY: ${{ secrets.BUDDY_API_KEY }}
  BUDDY_BASE_URL: ${{ secrets.BUDDY_BASE_URL }}
  BUDDY_MODEL: ${{ secrets.BUDDY_MODEL }}
  APP_ENV: "ci"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
